apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: data-0-my-cluster1-kafka-1
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 100Gi
  storageClassName: gp3-retain-csi
  volumeMode: Filesystem
  volumeName: pvc-9ab49e63-a693-495e-8c0f-cc2d7b857cff
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: data-my-cluster1-zookeeper-0
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 100Gi
  storageClassName: gp3-retain-csi
  volumeMode: Filesystem
  volumeName: pvc-5f0e97d9-e3a9-4ced-bec3-d7b0f3da022a
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: data-my-cluster1-zookeeper-1
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 100Gi
  storageClassName: gp3-retain-csi
  volumeMode: Filesystem
  volumeName: pvc-401e5232-094f-46d6-8fda-307b15821aa3
---  
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: data-my-cluster1-zookeeper-2
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 100Gi
  storageClassName: gp3-retain-csi
  volumeMode: Filesystem
  volumeName: pvc-9ebc7228-dcb4-4918-8e22-30996574ce16
---  
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: data-0-my-cluster1-kafka-2
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 100Gi
  storageClassName: gp3-retain-csi
  volumeMode: Filesystem
  volumeName: pvc-81522752-321e-4a8d-b273-eb196fab1da0
---  
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: data-0-my-cluster1-kafka-0
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 100Gi
  storageClassName: gp3-retain-csi
  volumeMode: Filesystem
  volumeName: pvc-23fbf9a5-028a-4e1e-884f-b040b6cdd2a7
---    