kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: gp3-retain-csi
provisioner: ebs.csi.aws.com
parameters:
  encrypted: 'true'
  type: gp3
reclaimPolicy: Retain
allowVolumeExpansion: true
volumeBindingMode: WaitForFirstConsumer